services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: trial
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: <http://elasticsearch:9200>
    networks:
      - elk

networks:
  elk:
    driver: bridge